# Generated by Django 4.0.1 on 2022-02-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0002_customer_purchasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='purchaseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
